//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ODMS.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class ODMSEntitiesApi : DbContext
    {
        public ODMSEntitiesApi()
            : base("name=ODMSEntitiesApi")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblm_UserLogin> tblm_UserLogin { get; set; }
    
        public virtual ObjectResult<ApiUserLogin_Result> ApiUserLogin(string userName, string password)
        {
            var userNameParameter = userName != null ?
                new ObjectParameter("UserName", userName) :
                new ObjectParameter("UserName", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("Password", password) :
                new ObjectParameter("Password", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ApiUserLogin_Result>("ApiUserLogin", userNameParameter, passwordParameter);
        }
    
        public virtual ObjectResult<ApiGetSubRoute_Result> ApiGetSubRoute(Nullable<int> psrid, Nullable<System.DateTime> currentDate)
        {
            var psridParameter = psrid.HasValue ?
                new ObjectParameter("psrid", psrid) :
                new ObjectParameter("psrid", typeof(int));
    
            var currentDateParameter = currentDate.HasValue ?
                new ObjectParameter("CurrentDate", currentDate) :
                new ObjectParameter("CurrentDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ApiGetSubRoute_Result>("ApiGetSubRoute", psridParameter, currentDateParameter);
        }
    
        public virtual ObjectResult<ApiGetOutlet_Result> ApiGetOutlet(Nullable<int> psrid)
        {
            var psridParameter = psrid.HasValue ?
                new ObjectParameter("Psrid", psrid) :
                new ObjectParameter("Psrid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ApiGetOutlet_Result>("ApiGetOutlet", psridParameter);
        }
    
        public virtual ObjectResult<ApiGetSku_Result> ApiGetSku(Nullable<int> dbid)
        {
            var dbidParameter = dbid.HasValue ?
                new ObjectParameter("dbid", dbid) :
                new ObjectParameter("dbid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ApiGetSku_Result>("ApiGetSku", dbidParameter);
        }
    
        public virtual ObjectResult<ApiGetTradePromotion_Result> ApiGetTradePromotion(Nullable<int> dbid)
        {
            var dbidParameter = dbid.HasValue ?
                new ObjectParameter("dbid", dbid) :
                new ObjectParameter("dbid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ApiGetTradePromotion_Result>("ApiGetTradePromotion", dbidParameter);
        }
    
        public virtual ObjectResult<ApiGetTradePromotionDefinition_Result> ApiGetTradePromotionDefinition(Nullable<int> dbid)
        {
            var dbidParameter = dbid.HasValue ?
                new ObjectParameter("dbid", dbid) :
                new ObjectParameter("dbid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ApiGetTradePromotionDefinition_Result>("ApiGetTradePromotionDefinition", dbidParameter);
        }
    }
}
