//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ODMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_MainMenu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_MainMenu()
        {
            this.tbl_SubMenuSecond = new HashSet<tbl_SubMenuSecond>();
            this.tbl_SubMenu = new HashSet<tbl_SubMenu>();
        }
    
        public int Id { get; set; }
        public string MainMenuName { get; set; }
        public string Controller { get; set; }
        public string Action { get; set; }
        public Nullable<int> sl { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_SubMenuSecond> tbl_SubMenuSecond { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_SubMenu> tbl_SubMenu { get; set; }
    }
}
