//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ODMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Manu_Role_mapping
    {
        public int id { get; set; }
        public int Roleid { get; set; }
        public int MainMenuid { get; set; }
        public int SubMenuid { get; set; }
        public int SubMenuSecondid { get; set; }
    }
}
