//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ODMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbld_SKU_unit
    {
        public int id { get; set; }
        public string unit_name { get; set; }
        public string unit_short_name { get; set; }
        public string unit_code { get; set; }
        public string unit_description { get; set; }
        public int qty { get; set; }
        public double height { get; set; }
        public double width { get; set; }
        public double length { get; set; }
        public double weight { get; set; }
    }
}
