//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ODMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbld_AdjustmentStock
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbld_AdjustmentStock()
        {
            this.tbld_AdjustmentStockItem = new HashSet<tbld_AdjustmentStockItem>();
        }
    
        public int id { get; set; }
        public int dbid { get; set; }
        public System.DateTime date { get; set; }
        public int userid { get; set; }
        public System.DateTime Syatemdate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbld_AdjustmentStockItem> tbld_AdjustmentStockItem { get; set; }
    }
}
