//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ODMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbld_Route_Plan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbld_Route_Plan()
        {
            this.tbld_Route_Plan_Detail = new HashSet<tbld_Route_Plan_Detail>();
        }
    
        public int id { get; set; }
        public string route_plan_name { get; set; }
        public string route_plan_code { get; set; }
        public string route_plan_description { get; set; }
        public int db_id { get; set; }
        public int db_emp_id { get; set; }
        public System.DateTime creation_date { get; set; }
        public System.DateTime start_date { get; set; }
        public System.DateTime end_date { get; set; }
        public System.DateTime Modify_date { get; set; }
        public string created_by { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbld_Route_Plan_Detail> tbld_Route_Plan_Detail { get; set; }
    }
}
