//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ODMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbld_distributor_Route
    {
        public int RouteID { get; set; }
        public string RouteCode { get; set; }
        public string RouteName { get; set; }
        public int RouteType { get; set; }
        public System.DateTime CreateDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public int IsActive { get; set; }
        public int DistributorID { get; set; }
        public Nullable<int> ParentID { get; set; }
    }
}
