//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ODMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbld_Route_Plan_Detail
    {
        public int id { get; set; }
        public Nullable<int> route_plan_id { get; set; }
        public Nullable<int> route_id { get; set; }
        public Nullable<int> dbid { get; set; }
        public Nullable<int> db_emp_id { get; set; }
        public Nullable<System.DateTime> planned_visit_date { get; set; }
        public Nullable<System.DateTime> delivery_date { get; set; }
        public Nullable<int> no_of_outlet { get; set; }
    
        public virtual tbld_Route_Plan tbld_Route_Plan { get; set; }
    }
}
