//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ODMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbld_ReportList
    {
        public int id { get; set; }
        public string ReportCode { get; set; }
        public string ReportName { get; set; }
        public string ReportController { get; set; }
        public string ReportAction { get; set; }
        public string ReportType { get; set; }
    }
}
