//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ODMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbld_SKU_Brand
    {
        public int id { get; set; }
        public string element_name { get; set; }
        public string element_code { get; set; }
        public string element_description { get; set; }
        public int element_category_id { get; set; }
        public int parent_element_id { get; set; }
    }
}
