//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ODMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbld_management_employee
    {
        public int id { get; set; }
        public string sales_emp_code { get; set; }
        public string first_name { get; set; }
        public string sales_emp_address { get; set; }
        public int sales_role_id { get; set; }
        public int sales_manager_id { get; set; }
        public int login_user_id { get; set; }
        public int biz_zone_id { get; set; }
        public string email { get; set; }
    }
}
