//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ODMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbld_Route_Plan_Mapping
    {
        public int id { get; set; }
        public int db_id { get; set; }
        public int db_emp_id { get; set; }
        public int route_plan_id { get; set; }
        public int route_id { get; set; }
        public string day { get; set; }
    }
}
