//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ODMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbld_Outlet_new
    {
        public int Id { get; set; }
        public string OutletCode { get; set; }
        public string OutletName { get; set; }
        public string OutletName_b { get; set; }
        public string Location { get; set; }
        public string Address { get; set; }
        public string GpsLocation { get; set; }
        public string OwnerName { get; set; }
        public string ContactNo { get; set; }
        public int Distributorid { get; set; }
        public int HaveVisicooler { get; set; }
        public int parentid { get; set; }
        public int outlet_category_id { get; set; }
        public int grading { get; set; }
        public int channel { get; set; }
        public string Latitude { get; set; }
        public string Longitude { get; set; }
        public string picture { get; set; }
        public int IsActive { get; set; }
        public int verify_status { get; set; }
        public System.DateTime verifydate { get; set; }
        public int verify_by { get; set; }
        public int psr_id { get; set; }
        public System.DateTime createdate { get; set; }
    }
}
