//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ODMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbld_Target_Details
    {
        public int id { get; set; }
        public int target_id { get; set; }
        public int db_id { get; set; }
        public int sku_id { get; set; }
        public int Pack_size { get; set; }
        public double qtyinCS { get; set; }
        public double qtyinPS { get; set; }
        public double total_Qty { get; set; }
    }
}
