//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ODMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbld_SKU
    {
        public int SKU_id { get; set; }
        public string SKUName { get; set; }
        public int SKUsl { get; set; }
        public int SKUcode { get; set; }
        public string SKUdescription { get; set; }
        public int SKUtype_id { get; set; }
        public int SKUnodetype_id { get; set; }
        public int SKUStatus { get; set; }
        public System.DateTime SKUcreationdate { get; set; }
        public System.DateTime SKUlaunchdate { get; set; }
        public System.DateTime SKUexpirydate { get; set; }
        public int SKUbrand_id { get; set; }
        public int SKUcategoryid { get; set; }
        public double SKUVolume_ml { get; set; }
        public double SKUVolume_8oz { get; set; }
        public string SKUName_B { get; set; }
        public int SKUContainertypeid { get; set; }
        public int SKUlpc { get; set; }
        public int SKUUnit { get; set; }
    }
}
