//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ODMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbll_inventory_log
    {
        public int id { get; set; }
        public Nullable<int> db_id { get; set; }
        public Nullable<int> sku_id { get; set; }
        public Nullable<int> batch_id { get; set; }
        public Nullable<double> price { get; set; }
        public Nullable<int> tx_qty_ps { get; set; }
        public Nullable<int> tx_type { get; set; }
        public Nullable<System.DateTime> tx_System_date { get; set; }
        public Nullable<System.DateTime> tx_date { get; set; }
        public Nullable<int> tx_challan { get; set; }
    }
}
