//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ODMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblm_UserLogin
    {
        public int id { get; set; }
        public System.DateTime Date { get; set; }
        public System.DateTime Date_time_stamp { get; set; }
        public int PSR_id { get; set; }
        public string current_lat { get; set; }
        public string current_lon { get; set; }
    }
}
