//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ODMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblm_visicooler_info
    {
        public int id { get; set; }
        public System.DateTime date { get; set; }
        public int Psr_id { get; set; }
        public int sub_route_id { get; set; }
        public int outlet_id { get; set; }
        public int purity_id { get; set; }
        public int charging_id { get; set; }
        public string image_upload { get; set; }
        public int order_qty_CS { get; set; }
        public System.DateTime order_date_time { get; set; }
    }
}
