//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ODMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblt_Challan_line
    {
        public int id { get; set; }
        public int challan_id { get; set; }
        public int sku_id { get; set; }
        public int batch_id { get; set; }
        public double price { get; set; }
        public int Pack_size { get; set; }
        public int Order_qty { get; set; }
        public int Extra_qty { get; set; }
        public int Free_qty { get; set; }
        public int Total_qty { get; set; }
        public int Confirm_qty { get; set; }
        public int Confirm_Free_qty { get; set; }
        public double Return_qty { get; set; }
        public double Order_qty_price { get; set; }
        public double Extra_qty_price { get; set; }
        public double Total_qty_price { get; set; }
        public double Confirm_qty_price { get; set; }
    
        public virtual tblt_Challan tblt_Challan { get; set; }
    }
}
