//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ODMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblt_Order_line
    {
        public int id { get; set; }
        public int Orderid { get; set; }
        public int Bundelitmeid { get; set; }
        public int sku_id { get; set; }
        public int Betch_id { get; set; }
        public int Pack_size { get; set; }
        public double unit_sale_price { get; set; }
        public int sku_order_type_id { get; set; }
        public int promotion_id { get; set; }
        public int lpec { get; set; }
        public int quantity_ordered { get; set; }
        public int quantity_confirmed { get; set; }
        public int quantity_delivered { get; set; }
        public double total_sale_price { get; set; }
        public double total_discount_amount { get; set; }
        public double total_billed_amount { get; set; }
    
        public virtual tblt_Order tblt_Order { get; set; }
    }
}
