//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ODMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblt_System
    {
        public int SystemId { get; set; }
        public int DBid { get; set; }
        public System.DateTime CurrentDate { get; set; }
        public System.DateTime PreviousDate { get; set; }
        public System.DateTime NextDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
    }
}
