//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ODMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblt_TradePromotionDefinition
    {
        public int id { get; set; }
        public int promo_id { get; set; }
        public int rule_type { get; set; }
        public int promo_line_type { get; set; }
        public int condition_type { get; set; }
        public int offer_type { get; set; }
        public int condition_sku_id { get; set; }
        public int condition_sku_Batch { get; set; }
        public int condition_sku_pack_size { get; set; }
        public int condition_sku_amount { get; set; }
        public int offer_sku_id { get; set; }
        public int offer_sku_pack_size { get; set; }
        public int offer_sku_Batch { get; set; }
        public int offer_sku_amount { get; set; }
        public int condition_bundle_qty_CS { get; set; }
        public Nullable<int> condition_sku_group { get; set; }
    
        public virtual tblt_TradePromotion tblt_TradePromotion { get; set; }
    }
}
