//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ODMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblt_inventory
    {
        public int id { get; set; }
        public int dbId { get; set; }
        public int skuId { get; set; }
        public int packSize { get; set; }
        public int BundleItemid { get; set; }
        public int batchNo { get; set; }
        public int qtyPs { get; set; }
    }
}
