//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ODMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblt_Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblt_Order()
        {
            this.tblt_Order_line = new HashSet<tblt_Order_line>();
        }
    
        public int Orderid { get; set; }
        public string so_id { get; set; }
        public string local_so_id { get; set; }
        public int route_id { get; set; }
        public int outlet_id { get; set; }
        public int Challan_no { get; set; }
        public System.DateTime planned_order_date { get; set; }
        public System.DateTime order_date_time { get; set; }
        public System.DateTime shipping_date { get; set; }
        public System.DateTime delivery_date { get; set; }
        public int db_id { get; set; }
        public int psr_id { get; set; }
        public int so_status { get; set; }
        public Nullable<double> total_order { get; set; }
        public Nullable<double> total_confirmed { get; set; }
        public Nullable<double> total_delivered { get; set; }
        public Nullable<int> sales_order_type_id { get; set; }
        public Nullable<double> manual_discount { get; set; }
        public int isProcess { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblt_Order_line> tblt_Order_line { get; set; }
    }
}
