//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ODMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblt_Challan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblt_Challan()
        {
            this.tblt_Challan_line = new HashSet<tblt_Challan_line>();
        }
    
        public int id { get; set; }
        public string challan_number { get; set; }
        public int db_id { get; set; }
        public int psr_id { get; set; }
        public string psr_Name { get; set; }
        public int route_id { get; set; }
        public string route_Name { get; set; }
        public int challan_status { get; set; }
        public int No_of_memo { get; set; }
        public int No_of_Outlet { get; set; }
        public System.DateTime order_date { get; set; }
        public System.DateTime delivery_date { get; set; }
        public System.DateTime Create_date_time { get; set; }
        public System.DateTime System_date { get; set; }
        public double grand_total_CS { get; set; }
        public double delivery_grand_total_CS { get; set; }
        public double grand_total { get; set; }
        public double delivery_grand_total { get; set; }
        public Nullable<int> challantype { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblt_Challan_line> tblt_Challan_line { get; set; }
    }
}
